# Generated by Django 5.1.1 on 2024-09-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='experience',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Proficient', 'Proficient')], default='Beginner', max_length=20),
        ),
    ]
