# Generated by Django 5.1.1 on 2025-01-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gallery_projectdetail_nextstep_challenge_technology'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectdetail',
            table='projects_details',
        ),
    ]
