# Generated by Django 5.1.1 on 2025-02-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_gallery_image_gallery_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
