name: Deploy Django Settings

on:
  push:
    branches:
      - main
      - test
      - dev

jobs:
  update-settings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Select and Upload Settings File
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            cp my-django-api/settings_prod.py my-django-api/settings.py
          elif [[ $GITHUB_REF == refs/heads/test ]]; then
            cp my-django-api/settings_test.py my-django-api/settings.py
          else
            echo "Using local settings.py"
          fi

      - name: Push Updated settings.py
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add my-django-api/settings.py
          git commit -m "Update settings.py for branch $GITHUB_REF_NAME"
          git push
